[package]
name = "ipurge"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
cron = "0.15.0"
ftail = "0.3.0"
log = "0.4.27"
reqwest = "0.12.20"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
